import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import StoreProvider from "@/providers/storeProvider";
import { ThemeProvider } from "@/providers/themeProvider";
import Layout from "@/components/layout/layout";

const iranSanse = localFont({
  src: [
    {
      path: "../../public/fonts/IranSansX/Webfonts/fonts/woff2/IRANSansX-Regular.woff2",
      weight: "normal",
      style: "normal",
    },
    {
      path: "../../public/fonts/IranSansX/Webfonts/fonts/woff2/IRANSansX-Bold.woff2",
      weight: "bold",
      style: "normal",
    },
    {
      path: "../../public/fonts/IranSansX/Webfonts/fonts/woff2/IRANSansX-Heavy.woff2",
      weight: "1000",
      style: "normal",
    },
    {
      path: "../../public/fonts/IranSansX/Webfonts/fonts/woff2/IRANSansX-ExtraBlack.woff2",
      weight: "950",
      style: "normal",
    },
    {
      path: "../../public/fonts/IranSansX/Webfonts/fonts/woff2/IRANSansX-Black.woff2",
      weight: "900",
      style: "normal",
    },
    {
      path: "../../public/fonts/IranSansX/Webfonts/fonts/woff2/IRANSansX-ExtraBold.woff2",
      weight: "800",
      style: "normal",
    },
    {
      path: "../../public/fonts/IranSansX/Webfonts/fonts/woff2/IRANSansX-DemiBold.woff2",
      weight: "600",
      style: "normal",
    },
    {
      path: "../../public/fonts/IranSansX/Webfonts/fonts/woff2/IRANSansX-Medium.woff2",
      weight: "500",
      style: "normal",
    },
    {
      path: "../../public/fonts/IranSansX/Webfonts/fonts/woff2/IRANSansX-Light.woff2",
      weight: "300",
      style: "normal",
    },
    {
      path: "../../public/fonts/IranSansX/Webfonts/fonts/woff2/IRANSansX-UltraLight.woff2",
      weight: "200",
      style: "normal",
    },
    {
      path: "../../public/fonts/IranSansX/Webfonts/fonts/woff2/IRANSansX-Thin.woff2",
      weight: "100",
      style: "normal",
    },
  ],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="fa" suppressHydrationWarning>
      <body className={`${iranSanse.className}`}>
        <StoreProvider>
          <ThemeProvider
            attribute="class"
            defaultTheme="dark"
            enableSystem
            disableTransitionOnChange
          >
            <Layout>{children}</Layout>
          </ThemeProvider>
        </StoreProvider>
      </body>
    </html>
  );
}
